### ISSUE TITLE
WordPress visual editor strips id attributes from div tags

### ISSUE THREAD

**Issue by oleonard** [Graffino/Clear-Floats-Button#1]
With the Clear Floats Button plugin enabled in WordPress 4.3.1, if I add a `<div>` with an id attribute the id attribute is stripped away by the visual editor:

```
1. Switch to the text editor and add `<div id="foo" class="bar">text</div>`.
2. Switch to the visual editor.
3. Switch back to the text editor. The markup now looks like `<div class="bar">text</div>`.
```

It looks like the problem is in line 56 of clear-floats-button.php:

`$init['extended_valid_elements'] = 'div[clear|style|class]';`

I assume this is overwriting a default configuration which allows `div[id]`, although I can't see where the default configuration is coming from. This plugin should at least append to the existing allowed attributes rather than overwrite them.

**Comment by oleonard** [comment]
This fix doesn't work for me. Appending to any existing `$init['extended_valid_elements']` might solve the problem for someone who has added a custom configuration which previously extended TinyMCE's valid elements for `<div>`, but the issue as I see it is that TinyMCE has a default configuration defining which attributes are valid for `<div>` which includes the id attribute, and this plugin's definition of valid attributes for `<div>` overrides it completely.

Perhaps the only solution is to find out exactly what attributes for `<div>` are allowed by default and make sure they are included in the plugin's definition?

**Comment by zenopopovici** [comment]
I've added the WP defaults available in https://core.trac.wordpress.org/browser/tags/4.3.1/src/wp-includes/kses.php
