### ISSUE TITLE
CSS Not Enqueued If User is NOT Logged into Admin

### ISSUE THREAD

**Issue by ldaughenbaugh** [Graffino/Clear-Floats-Button#2]
Love this plugin! But if a user is NOT logged into the admin, the CSS file with the clearfix styles is NOT enqueued. Thus the clearfixes are not applied when a visitor views the site. Was your intention that we'd have the clearfix styles in our theme style.css? That's what I've done now to get around the workaround. I see the issue on line 22 of clear-floats-button.php.

![css-not-enqueued](https://cloud.githubusercontent.com/assets/4234774/11042403/f3a6d9c0-86e4-11e5-8dd4-2b34909c508b.png)

**Comment by zenopopovici** [comment]
Sorry for being stupid ... I'll fix that. Soon. Meanwhile add the clearfix in your CSS.

**Comment by zenopopovici** [comment]
Fixed
