### ISSUE TITLE
InvalidCharacterError Issue In Internet Explorer

### ISSUE THREAD

**Issue by ldaughenbaugh** [Graffino/Clear-Floats-Button#3]
In Internet Explorer 11 and 10 on Windows 7 I noticed that NONE of the wysiwig editors in the WordPress admin display in IE. Plus, the textarea field never gets initiated and gets locked in a state that is not usable. I disabled all plugins and used the default twenty-fifteen theme with just the Clear-Floats-Button plugin and the issue remains. When I disable this plugin, the issue goes away.

I applied the exact same un-minified version of tinymce to trace the issue and the result is attached.

![ie](https://cloud.githubusercontent.com/assets/4234774/12950929/c674d712-cfdd-11e5-984e-57b471d14cdf.png)

I don't have the time to research or provide a suitable fix BUT I am able to implement a workaround by commenting out line #64 of clear-floats-button.php

![custom_elements_commented_out](https://cloud.githubusercontent.com/assets/4234774/12950930/c6771996-cfdd-11e5-8947-64f464777702.png)

With the "custom_elements" line commented out the wysiwig editors work fine. I can add, remove Clear Float buttons w/o issue and the result on the front-end is the same. Which lends me to think why is the "custom_elements" option even needed? Might not be suitable for everyone but again, this hack works for me for the time being. Hopefully you can provide a proper fix. Thanks.

**Comment by zenopopovici** [comment]
The custom elements is needed so that the editor doesn't strip out CSS classes, id's or other custom elements from the div.
Can you please test if custom classes or elements are stripped? I'm a bit busy right now and testing will take a while on my part.

**Comment by zenopopovici** [comment]
A misinterpretation of the tinymce API on my part. Will fix asap.

**Comment by zenopopovici** [comment]
@ldaughenbaugh Changes are now live on wordpress.org. Thanks a lot for your trouble!

**Comment by ldaughenbaugh** [comment]
Fantastic! I downloaded the latest version and confirmed all works as expected. Thank you very much.

**Comment by zenopopovici** [comment]
You're welcome :+1:
