### ISSUE TITLE
Why not just an inline style="clear:both;" attribute ?

### ISSUE THREAD

**Issue by mlang38** [Graffino/Clear-Floats-Button#5]
Hi !

This plugin is great and fixes an unbelievable lack in Wordpress image alignment feature. But I don't understand why you use _clearfix_ class and en-queue a whole style sheet when a basic inline style attribute would suffice. Furthermore your _clearfix_ style sheet overlaps with Foundation, Bootstrap or Compass ones what I think is not desirable.
If you need something to target the divs in the code to replace them, perhaps just an empty _clear-floats_ class would be sufficient ? And what the _divider_ class is for ?

Nevertheless, great plugin ! :+1:

**Comment by mlang38** [comment]
As an example, Foundation Sass _clearfix_ mixin include something for grids made with flexbox css, but it is overridden by your _clearfix_ class definition :
```sass
@mixin clearfix {
  &::before,
  &::after {
    content: ' ';
    display: table;
    @if $global-flexbox {
      flex-basis: 0;
      order: 1;
    }
  }

  &::after {
    clear: both;
  }
}
```

**Comment by zenopopovici** [comment]
As the clearfix style is standard, I don't see how it would conflict. In the example above there is no conflict. flex-basis and order would be preserved, the other values are the same.

I personally hate inline styling, I might need to modify it in the future and I like style to be separated from presentation, furthermore it's just 113bytes file.

The `divider` class is used to prevent inadvertent hijacking of empty `<div class="clearfix"></div>` which people tend to use a lot. A regex is performed there.

I just see implementation differences here, not a reason to change how things are right now.

**Comment by tyrann0us** [comment]
@zenopopovici, although I do understand you don't like inline styles there are several reasons to revert to it:
* WordPress' TinyMCE adds a lot of inline styles itself (`<p style="text-align: right;">Foobar</p>` for example) 
* Many themes already have their own clearfix included as @mlang38 noted
* The plugin's CSS files are enqueued on _every backend and frontend page_ (!) causing unnecessary requests on most pages

Suggestion: Change output to `<br style="clear: both;" />` or something similar and remove all CSS files.

I would really appreciate if you could reconsider this!
Thanks.

**Comment by zenopopovici** [comment]
I'm sorry but right now I view it as a technicality, that doesn't do much of improving the plugin.

Thank you for your suggestions, but I won't put in the time unless it is warranted. 

You're welcome to submit a PR with complete readme and version updates and I will merge it.

**Comment by tyrann0us** [comment]
> I'm sorry but right now I view it as a technicality, that doesn't do much of improving the plugin.

Well, of course it's something that won't improve anything visibly to the plugin and/or the user's workflow. Nevertheless, improving "under the hood" is equally important in my opinion.
> You're welcome to submit a PR with complete readme and version updates and I will merge it.

I'll do, tomorrow probably.
Thanks for your openness.

**Comment by tyrann0us** [comment]
@zenopopovici I noticed there are several things to improve, so I became maintainer of the [original plugin](https://wordpress.org/plugins/tinymce-clear-buttons/).
It just has been updated. This issue can be closed.
Thanks.

**Comment by zenopopovici** [comment]
@tyrann0us OK, I'll just borrow the code. (sarcasm)

**Comment by zenopopovici** [comment]
This was fixed.
