### ISSUE TITLE
1.1.0 release missing minified assets and svg icon

### ISSUE THREAD

**Issue by idpaterson** [Graffino/Clear-Floats-Button#8]
The distribution released to Wordpress does not include editor_plugin.min.js, clear.min.css, or clear.svg. The missing JS file causes the Divi editor to not load; rewriting the plugin to reference the non-minified source shows that other files are missing as well. 

As a temporary workaround, changing the reference from `.min.js` to `.js` allows the editor to load, but the plugin is not functional.

**Comment by zenopopovici** [comment]
Looking into it right now. Don't understand how this happened.

**Comment by zenopopovici** [comment]
SVN processing error. Sorry for that. Bumping version right now.

**Comment by zenopopovici** [comment]
@idpaterson It's now propagated, it should be available as an update. Sorry for the trouble.

Cheers,
Z.
