### ISSUE TITLE
Avoid overriding common keyboard shortcuts 

### ISSUE THREAD

**Issue by idpaterson** [Graffino/Clear-Floats-Button#9]
Cmd+F is a common shortcut initiating a search within the page. Perhaps a more esoteric shortcut would be better for the plugin as the number of people clearing floats frequently enough to use a keyboard shortcut is probably smaller than the number of people searching for text within their posts and pages.

**Comment by zenopopovici** [comment]
Hey @idpaterson,

It's actually ctrl+cmd+f. 
There's an error in the changelog.

Thanks for your report.

Cheers,
Z.

**Comment by idpaterson** [comment]
Perfect, that also explains why it didn't work for me ;)
